apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.cephfsCSIReclaimDeletedVolumes.serviceAccount }}
  namespace: {{ .Values.namespace }}

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: reclaim-volumes-patch-globaly
subjects:
  - kind: ServiceAccount
    name: {{ .Values.cephfsCSIReclaimDeletedVolumes.serviceAccount }}
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  # Use cephfs-csi-driver-ceph-csi-cephfs-provisioner to patch pvs
  # We need this to reclaim deleted volumes
  name: cephfs-csi-driver-ceph-csi-cephfs-provisioner
  apiGroup: rbac.authorization.k8s.io